const affirmations = [
    "You got this",
    "You'll figure it out",
    "You're a smart cookie",
    "I believe in you",
    "Sucking at something is the first step towards being good at something",
    "Struggling is part of learning",
    "Everything has cracks - that's how the light gets in",
    "Mistakes don't make you less capable",
    "We are all works in progress",
    "You are a capable human",
    "You know more than you think",
    "If everything was easy you'd be bored",
    "I admire you for taking this on",
    "You're resourceful and clever",
    "You'll find a way",
    "I know you'll sort it out",
    "Struggling means you're learning",
    "You're doing a great job",
    "It'll feel magical when it's working",
    "I'm rooting for you",
    "Your mind is full of brilliant ideas",
    "You make a difference in the world by simply existing in it",
    "You are learning valuable lessons from yourself every day",
    "You are worthy and deserving of respect",
    "You know more than you knew yesterday",
    "You're an inspiration",
    "Your life is about to be incredible",
    "Nothing is impossible. The word itself says 'I’m possible!'",
    "Failure is just another way to learn how to do something right",
    "I give myself permission to do what is right for me",
    "You can do it",
    "It is not a sprint, it is a marathon. One step at a time",
    "Success is the progressive realization of a worthy goal",
    "All you need is the plan, the roadmap, and the courage to press on to your destination",
    "The opposite of courage in our society is not cowardice... it is conformity",
    "Whenever we’re afraid, it’s because we don’t know enough. If we understood enough, we would never be afraid",
    "The past does not equal the future",
    "The path to success is to take massive, determined action",
    "It’s what you practice in private that you will be rewarded for in public",
    "Small progress is still progress",
    "Don't worry if you find flaws in your past creations, it's because you've evolved",
    "Starting is the most difficult step - but you can do it",
    "Don't forget to enjoy the journey",
    "It's not a mistake, it's a learning opportunity",
    "Every day is a new opportunity for success",
    "Challenges are stepping stones to my goals",
    "I trust in my ability to overcome obstacles",
    "I am constantly growing and evolving",
    "My potential is limitless",
    "I am resilient, strong, and brave",
    "I attract positivity into my life",
    "I am open to receiving abundance",
    "My thoughts create my reality, and I am in control",
    "I am worthy of love and respect",
    "I am surrounded by supportive and uplifting people",
    "I choose joy and gratitude in every moment",
    "I believe in my dreams and my ability to achieve them",
    "I radiate confidence, self-respect, and inner harmony",
    "I am a magnet for success and prosperity",
    "I release all doubts and embrace my power",
    "I am deserving of all the good things life has to offer",
    "I am the architect of my life; I build its foundation and choose its contents.",
    "I am in the process of becoming the best version of myself",
    "My life is a reflection of the energy I put into it",
    "I am a source of inspiration for others",
    "I am at peace with all that has happened, is happening, and will happen",
    "I am a magnet for miracles",
    "My possibilities are endless",
    "I release the need to compare myself to others",
    "I am surrounded by abundance in all areas of my life",
    "I am creating a life I love",
    "I am worthy of my dreams",
    "I trust the journey, even when I do not understand it",
    "I am deserving of success and happiness",
    "I choose to focus on what I can control and let go of what I can't",
    "I am courageous, and I stand up for myself",
    "I attract positive energy by being a positive person",
    "My mind is filled with peace, joy, and love",
    "I release all negative thoughts and embrace positivity",
    "I am resilient in the face of challenges",
    "I trust in my ability to create positive change",
    "I am a force for good in the world",
    "I am worthy of all the good things life has to offer",
    "I choose to be kind to myself and others",
    "I am on the path to success, and I trust the journey",
    "I am proud of all that I have accomplished",
    "I am open to receiving love and abundance",
    "I choose happiness, success, and abundance in my life",
    "I am a powerful creator, and I create the life I desire",
    "I am grateful for the positive changes happening in my life",
    "I am a magnet for opportunities, and I attract success effortlessly",
    "I am a beacon of confidence, strength, and positivity"
    
  ];
  
  export default affirmations;
  